name: challenge

on:
  push:
    branches: dev

jobs:
  print-ubuntu:
    name: print date on ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: fetch files to OS
      uses: actions/checkout@v2

    - name: print date
      run: date

  print-windows:
    name: print date on windows
    runs-on: windows-latest
    steps:
      - name: fetch files to OS
        uses: actions/checkout@v2
      
      - name: print date
        run: Get-Date

  calc-expression:
    needs: print-windows
    name: calculate the expression
    runs-on: ubuntu-latest
    steps:
      - name: fetch files to OS
        uses: actions/checkout@v2

      - name: calculate it
        run: 'bc <<< 4*5+7'