name: integration-code-quality

on:
  push: 
    branches: 'release/*'

jobs: 
  sonarcloud:
    name: code quality with sonarcloud
    runs-on: ubuntu-latest
    steps:
      - name: fetch files to OS
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Sonarcloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


